project_id = "rmswpurvnqqayemvuocv"

[functions.delivery-whatsapp]
verify_jwt = false

[functions.api-send-text]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false

[functions.amplopay-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.infinitepay-webhook]
verify_jwt = false